### PR TITLE
Jan30: Part One

### PR DESCRIPTION
**Pull request by hobinjk**
https://en-forum.guildwars2.com/topic/142673-game-update-notes-january-30-2024/

## Elementalist

- [x] Hammer outdated

## Engineer

- [x] Pistol outdated? "Blowtorch: Fixed an issue that caused this skill to inflict more burning than intended." 
- [x] Applied Force: Reduced the bonus power per might stack from 35 to 30 in PvE only.

## Guardian

- [x] Torch outdated

## Mesmer

- [x] Axe outdated
- [x] Illusionary Membrane: Reduced the condition damage bonus from 10% to 7% in PvE only.
- [x] Chaotic Persistence: unchanged (new from preview)

## Ranger

- [x] Untamed Axe outdated
- [x] Greatsword outdated
- [x] Devourer outdated

## Revenant

- [x] Leviathan Strength: Reduced the damage bonus from 15% to 10% in PvE only.

## Warrior

- [x] Blood Reaction: Increased the precision to ferocity conversion from 10% to 12% in PvE only.
- [x] Bloody Roar: Reduced the damage bonus from 20% to 15% in PvE only.

## Miscellaneous

- [x] Update disclaimer

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Does this invalidate the power berserker template? (Not sure if it was already kind of out of date, but.)

**Comment by hobinjk** [comment]
I marked it as outdated (#650?). It's a bit overly long text-wise to have both Approx and Outdated but I plan to bring it back to just Approx soon-ish

**Comment by marcustyphoon** [comment]
Yeah—do these changes make it any more out of date, though?

**Comment by marcustyphoon** [comment]
(Well —I suppose its coefficients being theoretically unchanged would only be correct if we have a perfect figure for what percentage of your damage is affected by berserk, which we probably don't. And in any case if it's to be updated soon it may as well be marked outdated :D)

**Comment by hobinjk** [comment]
Oh, in this PR it's "Power Berserker (Approx.) (Outdated)." A bit long (and a bit parenthetical). The template was up-to-date before the trait changes

I have a script for accurate damage per weapon but not for damage in berserk, could add that for the sake of science (I really should integrate all of these random scripts I'm writing into the developer section where they belong)

**Review by marcustyphoon — APPROVED** [review]

**Comment by marcustyphoon** [comment]
Oh, looks like it is, yeah. And not updated since the infinite berserk change, it seems, which gave it another signet.

**Pull request merged**
