### PR TITLE
Fix: trinkets disappear on their first load

### PR DESCRIPTION
**Pull request by marcustyphoon**
So, I have good news and bad news.

The good news is that this weird bug is fixed.

The bad news is that I fixed it by reverting gw2-ui all the way back to the version from 3 months ago.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
oh, wait. #335 immediately makes this not actually solve the problem. good meme

**Comment by gw2princeps** [comment]
Did you see that there is a gw2-ui version as dependency in react-discretize-components?

**Comment by marcustyphoon** [comment]
I did, yeah. We could revert that, but then when that component gets used in the main site, the main site will have 2 different versions of gw2-ui at the same time, which would be bad for bundle size.

**Comment by gw2princeps** [comment]
Sounds like we should fix the real problem :D

**Comment by gw2princeps** [comment]
Well, in the meantime, I suppose we can delay implementing the library on the mainsite until we figure out what to do with gw2-ui. Kicking the can. Yay

**Pull request closed without merging**
