### PR TITLE
Integrate react-discretize-components

### PR DESCRIPTION
**Pull request by gw2princeps**
This pull request implements the [react-discretize-components](https://github.com/discretize/react-discretize-components) library finally!
This implies a couple things: 
- The character blackbox is now no longer located in the optimizer repo 
- TextDivider and (in the future) other components overlapping with other discretize projects get moved into the components library. 
- update the profession images to the latest version

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Do you also want to update the core profession images?

**Comment by gw2princeps** [comment]
Thats not up to me. A secret contributor spent hours making these

**Comment by marcustyphoon** [comment]
Oh I just mean, because the core profession ones are just copies of the elite spec ones, but now they're the older ones!

**Comment by gw2princeps** [comment]
Can fix it or not. I dont mind

**Comment by marcustyphoon** [comment]
They get used for EoD professions rn, as well as core builds, so may as well update them!

**Review by marcustyphoon — APPROVED** [review]
Could use some handling for not having food or utility selected (empty slot instead of endlessly spinning) but we can add that later!

**Comment by gw2princeps** [comment]
Ah right, should add that as issue to the other repo

**Pull request merged**
