### PR TITLE
Chore: Convert Redux slices to Typescript

### PR DESCRIPTION
**Pull request by marcustyphoon**
Welp. We'll see how this goes.

---

This converts the Redux store/slices to Typescript, following the Redux and Redux Toolkit documentation to do so.

Adjustments performed include:
- Creating the Redux store in the module file instead of in an exported function; the build page thus has the same store. Is this fine? (Our setup is weird since we have no router.)
- Getting rid of a bunch of generic "get arbitrary key" selectors and "set arbitrary key" dispatch actions (can't type those) and replacing them with specific ones.
- Slight tweak to `infusionIds` to make its type simpler.

Not done:
- There's still a ton of `any` instead of actual types for various internal data structures, of course; I will work on typing the optimizer data via a JSON schema and then specifying those at a later point.
- Some reducers (the ones that import templates, basically) aren't typed, because, whatever.
- We have a load of junk re: types that are in weird places or are effectively duplicates; factoring can continue.
- I didn't do the build page slice.

### CODE REVIEW

**Comment by gw2princeps** [comment]
my hero

**Comment by marcustyphoon** [comment]
Still a draft; undrafting to get actions to run.

**Comment by marcustyphoon** [comment]
Running `yarn run tsc` currently yields:

---

Ignore for now:

- Various things in `functions/share/` that were there before.
- `src/state/slices/skills.ts:52:17 - error TS2339: Property 'profession' does not exist on type 'WritableDraft<{ skills: SkillsValues; }>'.` / `src/state/slices/traits.ts:107:17 - error TS2339: Property 'profession' does not exist on type 'WritableDraft<{ showAll: boolean; selectedLines: string[]; selectedTraits: number[][]; items: TraitsValues[]; }>'.` I think this is my code bug. I'll look at it in a future PR.

---

Would love some help with:

- `src/state/optimizer-parallel/modes/normal.ts:64:29 - error TS2345: Argument of type '"FINISHED"' is not assignable to parameter of type 'OptimizerStatus'.` This is from a mismatch between `/optimizer/status` and `workerMessageTypes`. Make consistent?

- `src/state/optimizer-parallel/worker/worker.ts:3:87 - error TS2307: Cannot find module 'wasm_module' or its corresponding type declarations.` Do we need to do "declare module" or something?

- `src/state/optimizer-parallel/worker/worker.ts:143:37 - error TS2345: Argument of type '{ Runes: string; Sigil1: string; Sigil2: string; Enhancement: string; Nourishment: string; }' is not assignable to parameter of type 'ExtrasCombination'.
  Property 'Relics' is missing in type '{ Runes: string; Sigil1: string; Sigil2: string; Enhancement: string; Nourishment: string; }' but required in type 'ExtrasCombination'.` This looks like an actual code bug; did I miss some things implementing relics?

---

I will fix:

- [ ] `src/state/slices/traits.ts:159:11 - error TS2339: Property 'eliteSpecializations' does not exist on type '{ readonly profession: "Warrior"; readonly eliteSpecializations: readonly ["Spellbreaker", "Berserker", "Bladesworn"]; } | { readonly profession: "Revenant"; readonly eliteSpecializations: readonly ["Herald", "Renegade", "Vindicator"]; } | ... 7 more ... | undefined'.` todo: refactor "PROFESSIONS" to key-value instead of array

**Comment by marcustyphoon** [comment]
Oops.

 - [ ] fix circular import breaking web workers

**Pull request merged**
