### PR TITLE
feat: implement upgraded character component

### PR DESCRIPTION
**Pull request by gw2princeps**
- Update gw2-ui version: Item supports a function as text prop now. 
- Update rdc to support the reworked character component with infusion toggle

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Hm, I assume the limiting factor on the rune font size is the fact that it has to be able to display both runes and infusions at once? I guess hiding the runes in infusion view mode could be kinda inconvenient for people wanting to screenshot them though.

**Comment by gw2princeps** [comment]
HIding the runes is not an option. 

we could assign different font sizes to infusions and runes though

**Comment by marcustyphoon** [comment]
Yeah, possibly. 

I don't think we can realistically go below the MUI "caption" font size for readable display text. I personally would probably not go much beneath 1rem for a primary info display.

Might be nice for layout to explicitly newline between multiple sigils on 2h weapons and multiple infusions instead of comma separating them and relying on the browser wrapping depending on word length, for consistency.

**Comment by marcustyphoon** [comment]
Also, CreateItem's new default icon doesn't respect the disableIcon prop! (see: affix select dropdown)

**Review by marcustyphoon — APPROVED** [review]

**Pull request merged**
