### PR TITLE
Modifier updates (mostly wvw splits)

### PR DESCRIPTION
**Pull request by hobinjk**
Also some very persnickety renames for consistency

Of note are the removal of stats on Heat the Soul and Eternal Champion, causing the removal of both trait's modifier data. Next, there's the movement of the healing modifier from Banshee's Wail to Life from Death, a minor fix for the heal scourge template

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Whoops, let me fix those lint errors on main.

**Comment by hobinjk** [comment]
Made #681 about the lint failure

**Comment by hobinjk** [comment]
Oh, I should have scrolled up!

**Comment by marcustyphoon** [comment]
Dang, we were (I was) missing a lot!

There is an argument to be made for keeping the trait id values the same (i.e. wrong), as loading a saved link will try to load traits by id value. But I don't think that feature gets used all that often anyway/old build links are useless over patches anyway, these are all traits whose absence shouldn't really matter, and the ids are exposed in the UI under applied modifiers so it's valuable for them to make sense! So I think I support fixing them.

**Review by marcustyphoon — APPROVED** [review]

**Comment by marcustyphoon** [comment]
Thanks for looking through these! This must have taken ages.

**Comment by hobinjk** [comment]
No problem! It wasn't too bad :D

Overall this was like 90% competitive splits which aren't really the most critical (superior siege golem benches when?) but it felt fun to tend to the garden of data

This also is only the existing traits, on a build-update-basis I'm planning to double check whether the balance team has snuck something in

**Pull request merged**
