### PR TITLE
Upgrade node to 17

### PR DESCRIPTION
**Pull request by gw2princeps**
Only thing that broke was eslint-plugin-jsdoc, therefore I upgraded that to the latest version. Asides from that all functionality appears to be working as before.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Not one for sticking to the stable versions, are you :D

**Comment by gw2princeps** [comment]
I'm traumatized by going through the muiv4 and gatsby3 upgrade ... ever since I try to keep up with latest

**Review by marcustyphoon — CHANGES_REQUESTED** [review]
Needs slight changes to the testModifiers/testPresets scripts because they use --experimental-json-modules to import a json file and I guess that's changed. Probably easiest to just use fs.readfilesync. may do this later if not lazy

**Comment by gw2princeps** [comment]
I guess this one is solved with vite too then

**Pull request closed without merging**
