### PR TITLE
Refactor: Add "outgoing" to damage mod keys

### PR DESCRIPTION
**Pull request by marcustyphoon**
This adds "outgoing" to the beginning of most of the attribute names that can be used under the "damage" modifier type. This is more consistent with the modifier names in https://github.com/Mk-Chan/gw2combat and removes the ambiguity where, without context, "Condition Damage" could mean either a bonus number of points of the GW2 attribute or a percentage bonus to outgoing condition damage.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
@gw2princeps do you know why this crashes in multithreaded mode with "Error RuntimeError: unreachable"?

**Comment by marcustyphoon** [comment]
aha—I built with `wasm-pack build ./wasm_module --target web --debug` and added `extern crate console_error_panic_hook;` and `console_error_panic_hook::set_once();` to the calculate function. not sure if both of those were necessary.

 is it this?

```rust
pub const ATTRIBUTE_COUNT: usize = 96; // actually only 95 attributes, but we need to align to 64 bytes;
```

**Comment by gw2princeps** [comment]
Those crates help with debugging - as the name suggest. 

I think those lines are indeed at fault. Some other character attribute arrays require the amount of attributes for array initialization. afaik there was no better way of enumerating enums.

**Comment by marcustyphoon** [comment]
I don't know about the performance optimization stuff, so I don't know the best change to make here!

**Comment by gw2princeps** [comment]
Seems fine to me now

**Pull request merged**
