### PR TITLE
Nov29 Mesmer Updates

### PR DESCRIPTION
**Pull request by hobinjk**
Received permission from FidelOo for staff mirage

gs qchrono is taking this weird mix of conc sigil on shield and impact on gs so I did a whole thing that I'll copy from the commit message for visibility:

Notably the build now uses a mix of concentration sigil on shield and
impact sigil on gs so I changed the extras for it while pretending it
only takes conc sigil (overapproximation, there's a missing half of an
impact sigil) and reducing the power coeff by the approximate
1.015 multiplicative from half-impact (was 3268 before)

### CODE REVIEW

**Comment by marcustyphoon** [comment]
There's an interesting scenario, for sure. If you want 10% boon duration on both weapon sets, there's a slightly superior setup, but the conc-on-shield setup seems better of course.



Trying to think how to make the result of just selecting and running the template have 10% boon duration rather than zero, which I think makes the most sense when zero isn't enough. That could be a minimum 10% boon duration (which leads to this - not so useful), only enabling conc sigil as the offhand sigil, or both.

**Comment by hobinjk** [comment]
I think I agree that min 10% is the most reasonable. From the video description as well, "This is because I do not recommend that you take Impact on the Greatsword set in real fights unless you are extremely confident in your abilities to upkeep quickness. Unless I'm optimizing for something specific or know that phases will be short, as quickness only gets tight towards the second continuum split, enough I would also opt into taking Concentration on the Greatsword set, especially in pugs."

**Comment by marcustyphoon** [comment]
Yeah, I think we have to put boon duration on somehow. The concentration sigil build certainly seems like the best, though; for clarity and to have a fast template for those just trying to determine which assassin pieces to use, I made another template that's just that as well.

(I recognize that I tend to err too far on the side of providing way too much information/too many options to users without guidance, but I think philosophically I'd rather people have to ask clarifying questions then assume that they fully understand a simpler presentation of a subset of info and then confidently say incorrect information in an internet argument. I assume the first thing doesn't actually help with the second thing in a meaningful way, but... still.)

**Comment by hobinjk** [comment]
For sure! I agree with the addition of 10% to the template name, it's good to add the clarification

**Pull request merged**
