### PR TITLE
Rework state-{from/to}-url (saga) logic

### PR DESCRIPTION
**Pull request by gw2princeps**
What has been done: 
- separate the sagas into smaller files
- build page compression / decompression is now a saga
- simplified the logic in the modals a bit thanks to moving all the compression logic into the saga

Questions for the review:
- where should we store the url of the generated build page? Ideally I would keep them near the character it belongs to ( not sure if that would break anything)? 
- How would I retrieve a value from a saga? at the moment I use a callback: https://github.com/discretize/discretize-gear-optimizer/blob/b6a320c59c37d0fed05c328c7f3d67a0ec309bd6/src/components/sections/results/BuildShareModal/BuildShareModal.jsx#L45-L55 
  Feels like this might break a convention or two.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
I believe the most clear way to do this is to move from manually passing callbacks around to returning Promises!

```js
// object-compression library

/**
 * @returns {Promise<String>} result
 */
const compress = ({ object, schema, onSuccess }) => {
  const transformed = transform(object, schema);
  return lib.compress(transformed);
}
```
```js
// jsx

const onClick = () => {
  // fixes the browser protection against window opening without any user interaction due to opening the window in a callback
  const windRef = window.open('', '_blank');

  dispatch({
    type: SagaTypes.ExportBuildPageState,
    windRef,
  });
};
```
```js
// saga

function* exportStateCharacter({ windRef }) {
  // ...
  const result = yield compress({
    object,
    schema: BuildPageSchema,
  });
  // ...
  if (windRef) windRef.location.href = /* whatever */
}
```

(Might be a couple bugs in this example code; I didn't actually test it)

**Comment by gw2princeps** [comment]
There you execute logic from the component in the saga tho. We have different actions to perform: 
1. open in new tab 
2. just copy to clipboard
So ultimately it doesnt change anything regardless of if you use a callback or a promise

**Comment by marcustyphoon** [comment]
Note that if you wanted to output a Promise from your code in order to allow for modern API uses but needed to keep using callbacks internally, you could use the `new Promise` wrapper that converts from one to the other like this:

```diff
- const compress = ({ object, schema, onSuccess }) => {
+ const compress = ({ object, schema, onSuccess }) => new Promise(resolve => {
  // function body goes here
-  onSuccess(whatever);
+  resolve(whatever);
+ }
}
```

**Comment by marcustyphoon** [comment]
> There you execute logic from the component in the saga tho. We have different actions to perform:
> 
> 1. open in new tab
> 2. just copy to clipboard
> 
> So ultimately it doesnt change anything regardless of if you use a callback or a promise

I made two changes in that example - oops, should have explained them separately for clarity!

1) By using Promises, you don't have to do the channel thing anymore; you can just do `const result = yield compress(whatever)`.

2) If you want to remove as much asynchronous code from your JSX UI code file as possible, you would pass what action you wanted to do as part of the dispatched effect and the saga would contain the code to actually do it. e.g.

```js
// saga

import { withPrefix } from 'gatsby';

function* exportStateCharacter({ windRef, writeClipboard }) {
  // ...
  if (windRef) windRef.location.href = /* whatever */;
  if (writeClipboard) {
    navigator.clipboard.writeText(
      window.location.href.slice(0, window.location.href.length - 1) + withPrefix(result),
    );
  }
}
```

You totally don't have to do this, but you could. Depends how complex the actual action you want to take is.

**Comment by gw2princeps** [comment]
Yeah, that would work of course. I'll get on it. I hoped I could dodge it haha

**Comment by marcustyphoon** [comment]
I don't think either is at all necessary, but if you did want to avoid passing callbacks in the redux actions, I think that's how you'd do it!

Unfortunately, the need to pass the window ref still means that action won't be serializable. As far as I can tell, though, the only reasons it's useful to have serializable actions are to make redux devtools have more understandable output and to integrate with testing libraries, and even if we wanted to do those things, this particular bit not being serializable seems fine.

**Review by marcustyphoon — APPROVED** [review]
Was going to go through this more carefully but it's big diff of mostly moving stuff around, so as long as it seems to function 👍 

We can probably rename `sagas.js` to e.g. `calculationSaga.js` now!

**Pull request merged**
