### PR TITLE
Migrate to pnpm

### PR DESCRIPTION
**Pull request by marcustyphoon**
Migrates from the quite-outdated-and-slow yarnv1 to pnpm.

Because pnpm allows one to run package scripts as `pnpm [name of package script]` just like yarn, the only practical change required of the developer is remembering to type `pnpm` instead of `yarn`. Of course, as a one-time action after this is merged, devs should `rm -r node_modules` and `pnpm install`.

This removes the need to cache `node_modules` for CI speed (which keeps getting cache evicted and isn't generally regarded as a best practice), and adds built-in dependency patching and what I hope is an actually-working `pnpm link` command.

(It would also be possible to convert the webassambly module into another package in a PNPM monorepo, which would be less hacky than just having it in a subfolder and [importing a path that doesn't exist](https://github.com/discretize/discretize-gear-optimizer/commit/abefc2d6a5c35333b87d2ff75da4f17d35745f8a), as we currently do.)

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Oh—the issue with this is that I don't know how to update the dockerfile. Not that we're currently using it, but.

**Review by hobinjk — APPROVED** [review]
Passes the rigorous "works on my computer" test

**Comment by marcustyphoon** [comment]
Oh, would this be a problem re: submoduling this repository into the main site? I see the other Discretize projects are all using yarnv1, and presumably it's much easier using the same package manager for them all. (I tried to get cute and do `pnpm -r install` in the main site repo to save myself time taking a look at it, figuring that minor versions don't really matter, but it explodes nicely because of postinstall scripts that try to lint the generated lockfile. Maybe if we migrate all of them someday.)

**Comment by gw2princeps** [comment]
Thats not a primary concern. The website rewrite pins an older commit at the moment and doesn't even utilize the optimizer (yet). We can slowly migrate all the projects to pnpm.

**Review by gw2princeps — APPROVED** [review]

**Pull request merged**
