### PR TITLE
Two small fixes

### PR DESCRIPTION
**Pull request by gw2princeps**
# Trait bug
When saving multiple results, going back to a previously saved one and sharing the link would use the current state of the form for the traits. This is wrong however, since a previously saved result might have a different trait selection. 

This PR fixes this behaviour by using the state provided by `character.settings.cachedFormState` instead of the global form one. 

# Infusions bugs
Infusions are not taken into consideration when sharing a build. The root issue for this is that while the character component already supports infusion handling, the compressed state did not include the infusions. 
The issue there was that the infusions object would contain arbitrary keys such as: 
```
{ Mighty: 2, Malign, 3 }
```
This is impossible to include into the compression library, therefore I opted for stringifying this object. Not efficient, but works. 

This however breaks old urls, due to the updated schema being larger than the previous one. Question is, do we care about it? Do we want to take the opportunity to build a system that can load old schemas depending on the version number?

### CODE REVIEW

**Comment by marcustyphoon** [comment]
In this case, can we fallback this? e.g. `infusions: JSON.parse(action.payload.character.infusions || 'null')`?

**Comment by gw2princeps** [comment]
This will not work unfortunately. If the new key was appended to the end of the schema, maybe, but since it is appended to the character part, which is in the middle of the list of values, there is no way of knowing which value was added.

**Comment by marcustyphoon** [comment]
Ah, I see. Right. Well, would we be able to guarantee that generally speaking older URLs could be made to work if we did add versioning? Only in the case of additions to the schema, I suppose, right? Which I guess should be most cases.

**Comment by gw2princeps** [comment]
Yep! When the underlaying component api changes we are out of luck

**Comment by gw2princeps** [comment]
I've added now a simple versioning for schema upgrades. I'm not sure if I am allowed to do the dynamic imports for the schemas like I did (https://github.com/discretize/discretize-gear-optimizer/blob/41457e75b2dc7d6425b6cfeaa7733e1dae4818bb/src/pages/build/index.jsx#L67). Please verify. 

The versioning assumes the version 0 when no `v` paramater is present in the url. Creating a new schema is very easy by copy pasting an existing schema, exchanging the version numbers and adjusting the import in the file `BuildShareModal.jsx`. 

I also added the profession pictures for the EoD specs.

**Review by marcustyphoon — COMMENTED** [review]
Gonna assume the main page URL still works since I can't test with the current path prefix setup.

**Review by marcustyphoon — APPROVED** [review]

**Pull request merged**
