### PR TITLE
Feat: Implement unbuffed simulation in core/data

### PR DESCRIPTION
**Pull request by marcustyphoon**
[no previews]

### CODE REVIEW

**Comment by marcustyphoon** [comment]
todo: implement hero panel critical damage separate from calculated critical damage

**Comment by gw2princeps** [comment]
holy shit, this is cool

**Comment by marcustyphoon** [comment]
The things I did to the core simulation code are Kind Of Horrible, but I've been doing that ever since multiple extras combinations, frankly :D Technical debt? What's that?

Anyway, if you have any ideas for the UI for this, I'd love 'em.

**Comment by marcustyphoon** [comment]
Merging the core and data changes now to reduce merge conflict potential.

**Pull request merged**
