### PR TITLE
Oct templates part two

### PR DESCRIPTION
**Pull request by hobinjk**
- [x] Receive permission from Tiramichu to use their log
- [x] Receive permission from Cemox to use their log

### CODE REVIEW

**Comment by marcustyphoon** [comment]
- [ ] Should condi quick untamed be marked outdated?
- [ ] What's the scenario with power deadeye? I see a change to 2h and no coefficient update.
- [ ] Missing relic on power vindi

(I don't know if you actually have the ability to interact with these checkboxes!)

**Comment by hobinjk** [comment]
Oh dear! I've pushed updates addressing those. Not sure how the deadeye thing happened, that's super weird. Thank you for your eyes!

**Comment by marcustyphoon** [comment]
No idea :D Certainly happens though!

Should that template be set to 2h?

**Comment by hobinjk** [comment]
Yes, I left the template name as "Power Deadeye Daggers M7" but the rotation has evolved to be 39% rifle 61% dagger (in terms of damage). Writing all this out, I think I'll change it to "Power Deadeye M7" to reflect that it's no longer only daggers even though they still have the majority

**Comment by marcustyphoon** [comment]
Oh, gotcha—is that the right video/log, then?

**Comment by hobinjk** [comment]
Yes, those are both correct

**Comment by marcustyphoon** [comment]
Ah, whoops! I must not have pulled the new commits when I took a look earlier. Looks great now, thanks!

**Review by marcustyphoon — APPROVED** [review]

**Pull request merged**
