### PR TITLE
October preset updates

### PR DESCRIPTION
**Pull request by hobinjk**
Also adds Thief relic to all the baseline extras since it's pretty free to upkeep.

Adds new sigil for willbender and appends it to the list in the schema

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Think we should change the status message or leave it for now?

**Comment by hobinjk** [comment]
I'll push a minor wording change. Definitely not worth any big changes yet

**Comment by hobinjk** [comment]
Thanks for catching the Power Berserker translation by the way!

**Review by marcustyphoon — APPROVED** [review]
Looks great—thanks for all of your work as always!

**Pull request merged**
