### PR TITLE
June 25 Preview

### PR DESCRIPTION
**Pull request by hobinjk**
WIP. A few traits in the preview are major updates but don't have concrete numbers yet

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Oh wow I'm out of the loop—I didn't realize we had an upcoming balance patch!

**Comment by hobinjk** [comment]
This one also feels pretty minor (watch it get updated to include a billion random tweaks for the spear beta)

**Comment by hobinjk** [comment]
- [ ] Infinite Forge confirmed 10% but it's only on blade skills so it can't be simulated without a "% damage due to Blade skills" factor that might not be accurate
- [ ] All For One damage buff: +10% strike damage with an uptime
- [ ] Heightened Focus: Weird outgoing healing buff +10/15/20% adrenaline stage 2/3/4

**Comment by marcustyphoon** [comment]
- [ ] is cwb outdated?
 - [ ] do we know if soothing power is unconverted?
 - [ ] I would probably `???` the default on infinite forge and/or all for one if they're not really close to 100
 - [ ] cslb/cdruid slightly inaccurate from shortbow possibly? (might be close enough to ignore)

**Comment by hobinjk** [comment]
Throwing on a bonus:
- [ ] does the mantra change to fb change templates right after I, a fool, updated them? in this year? in this month? on this day?

**Comment by hobinjk** [comment]
Checked in game whether Soothing Power is unconverted though I'm not sure if I followed the right steps:
- Consumed Magnanimous tuning crystal
- Equipped trait -> 73 cdmg in hero panel
- Unequipped trait -> still 73 in hero panel

**Comment by hobinjk** [comment]
I think Condi Slb is unchanged since you are your pet? Not sure whether that skill threaded that needle correctly but ehh it's probably fine

**Comment by marcustyphoon** [comment]
Knowing arenanet, who knows, but yeah, probably fine! If anything it seems more probable that it would have been broken before. Would be pretty funny if it somehow benefits from your own stats twice now.

**Review by marcustyphoon — APPROVED** [review]

**Pull request merged**
